# Check that syntax is correct

name: imgCIFSyntaxandConformanceCheck

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
            - 'Examples/*.cif'

  pull_request:
    paths:
            - 'Examples/*.cif'

  workflow_dispatch:   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syntax:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: checkout
          uses: actions/checkout@v2
          
      # Check syntax of all CIF files
        - name: check_syntax
          uses: COMCIFS/cif_syntax_check_action@master
          with:
            check-directory: Examples
          id: cif_syntax_check
  conformance:
    runs-on: ubuntu-latest
    needs: syntax

    steps:
      - name: Get the cache
        uses: actions/cache@v2
        id: cache
        with:
                 path: ~/.julia
                 key: ${{ runner.os }}-julia-v2
                 
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
                version: '1.6'

      - name: Install Julia packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
               julia -e 'import Pkg;Pkg.add(["CrystalInfoFramework","Lerche","FilePaths","ArgParse"])'
               julia -e 'import Pkg;Pkg.add(url="https://github.com/jamesrhester/ImgCIFHandler.jl")' 
               julia -e 'import Pkg;Pkg.add(["Colors","Sixel","ImageInTerminal","ImageContrastAdjustment"])' 

      - name: checkout
        uses: actions/checkout@v2
        with:
                path: main
      - name: checkout imgCIF checker
        uses: actions/checkout@v2
        with:
                repository: jamesrhester/ImgCIFHandler.jl
                path: imgcifhandler 

      - name: Diagnostics
        run: |
            ls -a
            pwd
            which julia

      - name: check_all_files
        run: |
               julia -e 'using Pkg; Pkg.status()'
               for file in Examples/*.cif
               do      
                  echo "Checking $file"
                  julia -O0 ./imgcifhandler/tools/image_tests.jl $file
                  if [ $? != 0 ] 
                  then 
                    exit 1 ;
                  fi 
               done
